### ISSUE TITLE
Xcode 6.4 Support?

### ISSUE THREAD

**Issue by szweier** [neonichu/PuncoverPlugin#8]
I'm running Xcode 6.4 and I've generated my .gutter.json file which is located in the same directory as my xcodeproj but nothing is appearing in my gutter.

**Comment by neonichu** [comment]
Probably just needs the usual refresh of [compatibility UUIDs](http://buegling.com/blog/2014/6/5/xcode-6-plugins-and-you) as done [here](https://github.com/neonichu/PuncoverPlugin/commit/fad710cc8ab90c5d98e7243cef37dd342c30e91e) — would appreciate a PR, will otherwise do it myself once time permits.
